### ISSUE TITLE
How to send headers while connecting to websockert?

### ISSUE THREAD

**Issue by akshay3015** [navinilavarasan/rxWebSocket#14]
i need to send basic auth header while connecting to websocket . how can i do that? websocket backend uses STOMP

**Comment by akshay3015** [comment]
` websocket = new RxWebsocket.Builder()               .request()`


> RxWebsocket does have method which takes okhttp3 so i guess it is possible to pass headers. please help

**Comment by AnnKrepchenko** [comment]
the same issue
ive tried with Request.Builder(),  but seems it doesnt work

**Comment by AnnKrepchenko** [comment]
ive forked and added my own interceptor to okhttpClient in doConnect of RXWebSocket.java 
Will leave my pull request later with user's implementation

**Comment by akshay3015** [comment]
please do that

**Comment by navinilavarasan** [comment]
@AnnKrepchenko Please submit a PR if you have already done it,I think that would be a nice addition to have.

**Comment by AnnKrepchenko** [comment]
@navinilavarasan  its opened

**Comment by navinilavarasan** [comment]
I will look into it and merge it soon.Thanks

**Comment by navinilavarasan** [comment]
Closed as part of #15
