### ISSUE TITLE
Change event processor

### ISSUE THREAD

**Issue by rok5ek** [navinilavarasan/rxWebSocket#17]
PublishProcessor should be changed to BehaviorProcessor.

PublishProcessor: Processor that multicasts all subsequently observed items to its current {@link Subscriber}s.

BehaviorProcessor: Processor that emits the most recent item it has observed and all subsequent observed items to each subscribed.

**Comment by navinilavarasan** [comment]
Behavior processor makes sense...I will update it.

**Comment by navinilavarasan** [comment]
#18

**Comment by navinilavarasan** [comment]
Closed by #18
