### ISSUE TITLE
eventStream is not usable from ouside of rxWebSocket package

### ISSUE THREAD

**Issue by ydanneg** [navinilavarasan/rxWebSocket#4]
com.navin.flintstones.rxwebsocket.RxWebsocket#eventStream returns Flowable<RxWebsocket.Event> where Event is the nested NOT public interface.

https://github.com/navinilavarasan/rxWebSocket/blob/master/app/src/main/java/com/navin/flintstones/rxwebsocket/MainActivity.java#L52
this is what is impossible to do outside of com.navin.flintstones.rxwebsocket package.

screenshot: https://www.dropbox.com/s/4f125ltjwchva1p/Screenshot%202018-01-07%2001.48.05.png?dl=0

**Comment by navinilavarasan** [comment]
@ydanneg Thanks for pointing this,#6 would have fixed this.Try v1.01.
