### ISSUE TITLE
Application crashes when opened from recent apps 

### ISSUE THREAD

**Issue by perusudroid** [navinilavarasan/rxWebSocket#7]
**io.reactivex.exceptions.OnErrorNotImplementedException: Read error: ssl=0x556ca40490: I/O error during system call, Connection reset by peer
                                                       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)**

**Comment by navinilavarasan** [comment]
This bug is not in the library.The event stream in the sample app does not give a error handler.Though this would be fixed.

**Comment by perusudroid** [comment]
Also if I provide an websocket Url which is currently unavailable,
application crashes. And the log clearly shows it failed to connect to that
Url.

**Comment by navinilavarasan** [comment]
@Periyanayagam It is the same issue in the application.The application is a sample application with no real error handlers.This should be also be fixed with the same PR.
